language: python
python:
  - 2.7
  - 3.1
  - 3.2
  - pypy
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.4.1
# before_install:
#     - sudo apt-get install subversion bzr mercurial
#     - echo -e "[web]\ncacerts = /etc/ssl/certs/ca-certificates.crt" >> ~/.hgrc
install:
 - pip install nose
 - pip install -r requirements.txt
 - pip install -q Django==$DJANGO_VERSION
script: nosetests
# notifications:
  # irc: "irc.freenode.org#pip"
branches:
  only:
    - default
matrix:
  allow_failures:
env:
  - PIP_USE_MIRRORS=true