from django.utils.translation import ugettext_lazy as _

AWS_SEARCH_INDEX = {
    'All': _('All'),
    'Apparel': _('Apparel'),
    'Appliances': _('Appliances'),
    'Automotive': _('Automotive'),
    'Baby': _('Baby'),
    'Beauty': _('Beauty'),
    'Blended': _('Blended'),
    'Books': _('Books'),
    'Classical': _('Classical'),
    'DigitalMusic': _('Digital Music'),
    'DVD': _('DVD'),
    'Electronics': _('Electronics'),
    'ForeignBooks': _('Foreign Books'),
    'GourmetFood': _('Gourmet Food'),
    'Grocery': _('Grocery'),
    'HealthPersonalCare': _('Health & Personal Care'),
    'Hobbies': _('Hobbies'),
    'HomeGarden': _('Home & Garden'),
    'Industrial': _('Industrial'),
    'Jewelry': _('Jewelry'),
    'KindleStore': _('Kindle Store'),
    'Kitchen': _('Kitchen'),
    'LawnAndGarden': _('Lawn & Garden'),
    'Magazines': _('Magazines'),
    'Miscellaneous': _('Miscellaneous'),
    'MP3Downloads': _('MP3 Downloads'),
    'MusicalInstruments': _('Musical Instruments'),
    'Music': _('Music'),
    'MusicTracks': _('Music Tracks'),
    'OfficeProducts': _('Office Products'),
    'OutdoorLiving': _('Outdoor Living'),
    'PCHardware': _('PC Hardware'),
    'PetSupplies': _('Pet Supplies'),
    'Photo': _('Photo'),
    'Software': _('Software'),
    'SoftwareVideoGames': _('Software & Video Games'),
    'SportingGoods': _('Sporting Goods'),
    'Tools': _('Tools'),
    'Toys': _('Toys'),
    'VHS': _('VHS'),
    'VideoGames': _('Video Games'),
    'Video': _('Video'),
    'Watches': _('Watches'),
    'WirelessAccessories': _('Wireless Accessories'),
    'Wireless': _('Wireless'),
}
